### ISSUE TITLE
Add condition  to HPA remove sections on workflows

### ISSUE THREAD

**Issue by oap75** [dappforce/polkaverse#313]
### Current Behavior:

The CI just remove the HPA and if it does not exists the action will fail

### Expected Behavior:

Should bypass and keep going to the rest of steps and just notif us

### Steps To Reproduce:

remove HPA in production and run production actions 

## ✔️ Possible solutions

add an option to kubectl to bypass it. 

```sh
kubectl delete --ignore-not-found=true
```

**Comment by iv1310** [comment]
Can you share the failed CI link? @oap75

**Comment by oap75** [comment]
> Can you share the failed CI link? @oap75

https://github.com/dappforce/polkaverse/actions/runs/8170110159/job/22335805954#step:7:1

**Comment by iv1310** [comment]
Btw, why do we need to remove the hpa in the first place? 
I have an idea to just return `true` if the removable of the hpa is failed

**Comment by oap75** [comment]
> Btw, why do we need to remove the hpa in the first place?

Because of the cashing problem on front-end applications. If U have multiple instances of a front-end behind the cloud flare with different versions the clients will face caching issues and may see white pages for a while

**Comment by iv1310** [comment]
Anw, I don't have write access to the repo :") 

```
ERROR: Permission to dappforce/polkaverse.git denied to iv1310.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by oap75** [comment]
> Anw, I don't have write access to the repo :")
> 
> ```
> ERROR: Permission to dappforce/polkaverse.git denied to iv1310.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

@olehmell

**Comment by iv1310** [comment]
Resolved the issue https://github.com/dappforce/polkaverse/pull/316
