### ISSUE TITLE
Unable to view My Chats

### ISSUE THREAD

**Issue by ltfschoen** [dappforce/polkaverse#322]
### Current Behavior:

I logged in and created a new Grill Chat Group, I then created a first post. It was at this link https://grillapp.net/c/cc/clawbird-dao-86902?ref=12343

But now even after I choose the option to Login via Polkadot, even if I go to https://grillapp.net/c/my-chats, it doesn't load my chats 

Note that I was logged in with account 3ogM6BtcoDH5fhs7cRueXsngsVnd6E9kD48pxaR57NiULSr8, with username luke.sub.

If I instead go to https://grill.chat/my-chats, and login with that same account, it still loads My Chat there, but if I click "My Chats > Created" it doesn't list the new chat that I created when I was logged into https://grillapp.net

### Expected Behavior:

It should load my chats

### Steps To Reproduce:

As mentioned above

## Environment

Brave 1.63.162

**Comment by teodorus-nathaniel** [comment]
Sorry, I can't reproduce your bug, can you try it again?
Or maybe if its still persists, can you send a video of your reproduction?
